"""add unit and serving_weight to products

Revision ID: 6866f2b59003
Revises: 3d3c389bd789
Create Date: 2026-04-11 20:05:29.899310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6866f2b59003'
down_revision = '3d3c389bd789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('serving_weight', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('serving_weight')
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
