"""add created_by to products

Revision ID: 9fdf48d991c7
Revises: 657b7dcc972a
Create Date: 2026-03-30 10:03:01.895871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fdf48d991c7'
down_revision = '657b7dcc972a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
